import Vue from 'vue'
import {
    Container,
    Header,
    Footer,
    Aside,
    Main,
    Switch,
    Image,
    Row,
    Col,
    Avatar,
    Menu,
    Input,
    Select,
    Option,
    Button,
    Card,
    PageHeader,
    Autocomplete,
    Carousel,
    Pagination,
    Tabs,
    TabPane,
    Divider,
    Form,
    Tag,
    Badge,
    Upload,
    Collapse,
    Radio,
    Popover,
    ToolTip,
    InfiniteScroll
} from 'element-ui'
Vue.use(Container)
Vue.use(Header)
Vue.use(Footer)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Switch)
Vue.use(Image)
Vue.use(Row)
Vue.use(Col)
Vue.use(Avatar)
Vue.use(Menu)
Vue.use(Input)
Vue.use(Select)
Vue.use(Option)
Vue.use(Button)
Vue.use(Card)
Vue.use(PageHeader)
Vue.use(Autocomplete)
Vue.use(Carousel)
Vue.use(Pagination)
Vue.use(Tabs)
Vue.use(TabPane)
Vue.use(Divider)
Vue.use(Form)
Vue.use(Tag)
Vue.use(Badge)
Vue.use(Upload)
Vue.use(Collapse)
Vue.use(Radio)
Vue.use(Popover)
Vue.use(ToolTip)
Vue.use(InfiniteScroll)